### ISSUE TITLE
update: home and synthetic monitoring page

### ISSUE THREAD

**Issue by orcunilbeyli** [checkly/checklyhq.com#234]
## Tasks
- Home page
  - [ ] Copy update Synthetic Monitoring section, see design.
  - [ ] Update design with new screenshots.
- Synthetic monitoring page
  - Hero
    - [ ] Copy update sub-headline , see design.
    - [ ] Update screenshots
   - Features blocks
     - [ ] Update copy. Compare each block with design.
   - [ ] Add New section below video, see design
   - [ ] Move learn from community very bottom of the page, see design.

## Updated design
![image](https://user-images.githubusercontent.com/1042651/138592931-38ba242f-2480-4001-9a85-a37d7f070c62.png)
![image](https://user-images.githubusercontent.com/1042651/138592934-fb33f5c1-322c-4310-bd26-27f3c92bc2ce.png)
![image](https://user-images.githubusercontent.com/1042651/138592935-793d0671-fec7-43ca-be71-a30323c23989.png)

## Figma files
[Figma: Home](https://www.figma.com/file/et2KLDMVOPb0xeAmXFJXok/checklyhq.com?node-id=1791%3A3)
[Figma: Synthetic monitoring](https://www.figma.com/file/et2KLDMVOPb0xeAmXFJXok/checklyhq.com?node-id=320%3A0)
